/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Filip
 */
public class GameForm extends javax.swing.JFrame {

    /**
     * Creates new form GameForm
     */
    public GameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_score = new javax.swing.JLabel();
        pnl_grid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_score.setText("Score goes here");
        getContentPane().add(lbl_score, java.awt.BorderLayout.PAGE_END);

        pnl_grid.setBackground(new java.awt.Color(153, 153, 153));
        pnl_grid.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jPanel1.setLayout(new java.awt.BorderLayout());

        btn_1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_1.setFocusPainted(false);
        jPanel1.add(btn_1, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_2.setFocusPainted(false);
        jPanel2.add(btn_2, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        btn_3.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_3.setFocusPainted(false);
        jPanel3.add(btn_3, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        btn_4.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_4.setFocusPainted(false);
        jPanel4.add(btn_4, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        btn_5.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_5.setFocusPainted(false);
        jPanel6.add(btn_5, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());

        btn_6.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_6.setFocusPainted(false);
        jPanel5.add(btn_6, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel5);

        jPanel7.setLayout(new java.awt.BorderLayout());

        btn_7.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_7.setFocusPainted(false);
        jPanel7.add(btn_7, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        btn_8.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_8.setFocusPainted(false);
        jPanel8.add(btn_8, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        btn_9.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        btn_9.setFocusPainted(false);
        jPanel9.add(btn_9, java.awt.BorderLayout.CENTER);

        pnl_grid.add(jPanel9);

        getContentPane().add(pnl_grid, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addListener(ActionListener e1, ActionListener e2, ActionListener e3, ActionListener e4, ActionListener e5, 
            ActionListener e6, ActionListener e7, ActionListener e8, ActionListener e9){
        
        btn_1.addActionListener(e1);
        btn_2.addActionListener(e2);
        btn_3.addActionListener(e3);
        btn_4.addActionListener(e4);
        btn_5.addActionListener(e5);
        btn_6.addActionListener(e6);
        btn_7.addActionListener(e7);
        btn_8.addActionListener(e8);
        btn_9.addActionListener(e9);
        
        
    }
    /**
     * @param text
     * @param args the command line arguments
     */
    
    public void setLbl_scoreText(String text) {
        this.lbl_score.setText(text);
    }

    public void setBtn_1Text(String text) {
        this.btn_1.setText(text);
    }

    public void setBtn_2Text(String text) {
        this.btn_2.setText(text);
    }

    public void setBtn_3Text(String text) {
        this.btn_3.setText(text);
    }
    
    public void setBtn_4Text(String text) {
        this.btn_4.setText(text);
    }

    public void setBtn_5Text(String text) {
        this.btn_5.setText(text);
    }

    public void setBtn_6Text(String text) {
        this.btn_6.setText(text);
    }

    public void setBtn_7Text(String text) {
        this.btn_7.setText(text);
    }

    public void setBtn_8Text(String text) {
        this.btn_8.setText(text);
    }
    
    public void setBtn_9Text(String text) {
        this.btn_9.setText(text);
    }
    
    public void setBtn_1Color(Color c) {
        this.btn_1.setForeground(c);
    }

    public void setBtn_2Color(Color c) {
        this.btn_2.setForeground(c);
    }

    public void setBtn_3Color(Color c) {
        this.btn_3.setForeground(c);
    }
    
    public void setBtn_4Color(Color c) {
        this.btn_4.setForeground(c);
    }

    public void setBtn_5Color(Color c) {
        this.btn_5.setForeground(c);
    }

    public void setBtn_6Color(Color c) {
        this.btn_6.setForeground(c);
    }

    public void setBtn_7Color(Color c) {
        this.btn_7.setForeground(c);
    }

    public void setBtn_8Color(Color c) {
        this.btn_8.setForeground(c);
    }
    
    public void setBtn_9Color(Color c) {
        this.btn_9.setForeground(c);
    }

    public static String getBtn_1Text() {
        return btn_1.getText();
    }

    public static String getBtn_2Text() {
        return btn_2.getText();
    }

    public static String getBtn_3Text() {
        return btn_3.getText();
    }

    public static String getBtn_4Text() {
        return btn_4.getText();
    }

    public static String getBtn_5Text() {
        return btn_5.getText();
    }

    public static String getBtn_6Text() {
        return btn_6.getText();
    }

    public static String getBtn_7Text() {
        return btn_7.getText();
    }

    public static String getBtn_8Text() {
        return btn_8.getText();
    }

    public static String getBtn_9Text() {
        return btn_9.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_1;
    private static javax.swing.JButton btn_2;
    private static javax.swing.JButton btn_3;
    private static javax.swing.JButton btn_4;
    private static javax.swing.JButton btn_5;
    private static javax.swing.JButton btn_6;
    private static javax.swing.JButton btn_7;
    private static javax.swing.JButton btn_8;
    private static javax.swing.JButton btn_9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JPanel pnl_grid;
    // End of variables declaration//GEN-END:variables
}
