/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Filip
 */
public class OnlineForm extends javax.swing.JFrame {

    /**
     * Creates new form OnlineForm
     */
    public OnlineForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cg = new javax.swing.JButton();
        btn_jg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 0, 1));

        btn_cg.setText("CREATE GAME");
        jPanel1.add(btn_cg);

        btn_jg.setText("JOIN GAME");
        jPanel1.add(btn_jg);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addListener(ActionListener e1, ActionListener e2){
        btn_cg.addActionListener(e1);
        btn_jg.addActionListener(e2);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cg;
    private javax.swing.JButton btn_jg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
